vectordb:
  provider: pinecone
  config:
    metric: cosine
    vector_dimension: 768
    index_name: neuro-vault
    serverless_config:
      cloud: aws
      region: us-east-1

llm:
  provider: google
  config:
    model: gemini-1.5-flash
    # max_tokens: 1000
    # temperature: 0.5
    # top_p: 1
    # stream: false

embedder:
  provider: google
  config:
    model: 'models/embedding-001'
    task_type: "retrieval_document"
    title: "Embeddings for Embedchain"